### ISSUE TITLE
How to handle dynamic number of arguments?

### ISSUE THREAD

**Issue by HaveAGitGat** [nfischer/shelljs-exec-proxy#18]
Hi again,

I asked this on stackoverflow but didn't get an answer so thought it was worth asking here.

I'm using shelljs-exec-proxy with HandBrake and FFmpeg on Ubuntu, for example:

`shell.ffmpeg( '-i', 'source/path',  '-s','50x50', 'destination/path');`

This works fine, however, before using shelljs-exec-proxy, the  '-s','50x50', section was covered by a single parameter for the video file output settings e.g.:

```
var preset = '-s 50x50'
shell.exec(''ffmpeg -i' + 'source/path' +preset + 'destination/path');
```

The preset variable can have any number of arguments e.g.:

```
var preset = '-s 50x50 -ac 2'
shell.exec(''ffmpeg -i' + 'source/path' +preset + 'destination/path');
```

Is there a way for me to handle this with shelljs-exec-proxy? So I'd need one parameter to represent a bunch of arguments, something like this:

```
var arguments = '-s', '50x50', '-ac', '2'
shell.ffmpeg( '-i', 'source/path', arguments, 'destination/path');
```

**Comment by HaveAGitGat** [comment]
Someone suggested I put the arguments in an array e.g.:

```
var combined = ['-i', currentSourceLine, '-o', currentDestinationLine, '-Z', 'Very Fast 1080p30'] // This is an Array of arguments!
shell.HandBrakeCLI(...combined); // This uses argument destructuring
```

Will try this.

**Comment by HaveAGitGat** [comment]
Seems to work okay. The key issue then becomes correctly parsing a string. For example, this quirky string:

```
var preset = '--preset-import-file "C:\Users\HaveAGitGat\Desktop\test \" -Z "My Preset-"\' "- preset.json -Z file.json" -Z "My Preset-"'

console.log(convertToArgs(preset))

// [
// '--preset-import-file',
// 'C:\Users\HaveAGitGat\Desktop\test \" -Z "My Preset-"\' "- preset.json -Z file.json',
// '-Z',
//  'My Preset-',
// ]
```

Not sure if there's an algorithm/library which can correctly do this. I tried the string-argv module but it fails:

```
var args2 = stringArgv.parseArgsStringToArgv(
    preset,
);

// [ '--preset-import-file',
//   'C:UsersHaveAGitGatDesktop\test ',
//   '-Z',
//   'My Preset-',
//   '- preset.json -Z file.json',
//   '-Z',
//   'My Preset-' 
// ]
```

**Comment by nfischer** [comment]
I do not encourage trying to parse strings apart yourself; this can be error prone for things which intentionally have spaces (as you've observed).

I suppose the spread operator (`...someArray`) should otherwise be fine though.

**Comment by HaveAGitGat** [comment]
Yeah there are probably a million edge cases with parsing strings like this. Will need to think of a different approach.

Thanks.
