### ISSUE TITLE
non-existing prop warning

### ISSUE THREAD

**Issue by bise1157** [nfischer/shelljs-exec-proxy#20]
Hi,

I get a couple of non-existent property warnings (os x, bash).
Everything seems to work, so I am not sure if this is something to take care of...

Best
Ben

`(node:2246) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2246) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:2246) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
`

**Comment by nfischer** [comment]
This is a known shelljs issue, I just need to update the dependency in this project. I haven't tested this project against v0.8.*, but I'll try to validate that and ship out a new release of this project.

**Comment by nfischer** [comment]
This is fixed in PR #21. I'll look into cutting a new release for this.

**Comment by nfischer** [comment]
Try out v0.2.0. This should include the fix. If you notice any other issues with the package, please file a new GitHub issue.
